development:
  clients:
    default:
      uri: mongodb+srv://<%= ENV['MONGO_USERNAME'] %>:<%= ENV['MONGO_PASSWORD'] %>@socialconnect.rr4av.mongodb.net/social_connect_development?retryWrites=true&w=majority&appName=SocialConnect
      options:
        server_selection_timeout: 5

production:
  clients:
    default:
      uri: mongodb+srv://socialConnectProd:<%= ENV['MONGO_PASSWORD_PROD'] %>@prodsc.falgt.mongodb.net/SocialConnectProd?retryWrites=true&w=majority&authSource=admin
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      uri: mongodb+srv://socialconnectTest:<%= ENV['MONGO_PASSWORD_TEST'] %>@socialconnecttest.p9ssd.mongodb.net/social_connect_test?retryWrites=true&w=majority&appName=SocialConnectTest
      options:
        server_selection_timeout: 5 
